project:
  type: book
  output-dir: docs

book:
  title: "Multilevel Workshop"
  author: 
    - name: "Andrew Grogan-Kaylor"
      url: https://agrogan1.github.io/
  date: "today"
  cover-image: multilevel-workshop.png
  downloads: [pdf]
  twitter-card: true
  open-graph: true
  site-url: https://agrogan1.github.io/multilevel-workshop/
  search: true
  repo-url: https://github.com/agrogan1/multilevel-workshop
  repo-actions: [issue]
  sharing: [facebook, linkedin]
  chapters:
    - index.qmd
    - clustering.qmd
    - multilevel-workshop.qmd
    - multilevel-workshop2.qmd
    - references.qmd
    - license-and-citation.qmd
  navbar:
    background: "#00274C"

citation:
  url: https://agrogan1.github.io/multilevel-workshop/

bibliography: multilevel-workshop.bib

google-scholar: true

prefer-html: true

format:
  html:
    theme: 
      light: [yeti, theme-light.scss]
      dark: vapor
    css: multilevel-workshop.css
    lightbox: true
    execute:
      echo: true
      warning: false
      freeze: auto
  pdf:
    lot: true
    lof: true
    keep-tex: true
    execute:
      echo: true
      warning: false
      freeze: auto


